//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductOrder = new HashSet<ProductOrder>();
        }
    
        public int idProduct { get; set; }
        public string nameProduct { get; set; }
        public string descriptionProduct { get; set; }
        public string manufactureProduct { get; set; }
        public int priceProduct { get; set; }
        public Nullable<int> discountProduct { get; set; }
        public Nullable<int> countProduct { get; set; }
        public string photoProduct { get; set; }

        public int totalPrice
        {
            get 
            { 
                if (this.discountProduct != null && this.discountProduct > 0)
                {
                    int disount = (Convert.ToInt32(this.priceProduct * this.discountProduct) / 100);
                    return this.priceProduct - disount;
                }
                else
                {
                    return this.priceProduct;
                }
            }  
            set 
            {
            
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductOrder> ProductOrder { get; set; }
    }
}
